kind: pipeline
type: docker
name: release

trigger:
  ref:
    - refs/heads/main
    - refs/tags/*

steps:
  - name: build
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_api_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      dockerfile: Dockerfile